### ISSUE TITLE
have trouble in running reader.py

### ISSUE THREAD

**Issue by zhhongzhi** [berlino/SA-Sent#3]
Thanks for sharing the code. 
I'm reproducing the results.
The data files and Jar file is placed in the corresponding place. 
Then an error is  encountered in running tokenizer. 
```
INFO:CoreNLP_JavaServer: INPUT: 8000 documents, 397869 characters, 81940 tokens, 49.7 char/doc, 10.2 tok/doc RATES: 1047.806 doc/sec, 10732.2 tok/sec

> /Users/hongzhizhang/wp/sa_sentiment/SA-Sent/reader.py(125)to_index()
-> pdb.set_trace()
(Pdb) c
> /Users/hongzhizhang/wp/sa_sentiment/SA-Sent/reader.py(126)to_index()
-> if target_start < 0 or target_end < 0:  pdb.set_trace()
(Pdb) c
Traceback (most recent call last):
  File "reader.py", line 222, in <module>
    train, test = reader.read()
  File "reader.py", line 146, in read
    self.to_index(self.train_data)
  File "reader.py", line 126, in to_index
    if target_start < 0 or target_end < 0:  pdb.set_trace()
IndexError: list assignment index out of range
WARNING:CoreNLP_PyWrapper:Killing subprocess 42798
INFO:CoreNLP_PyWrapper:Subprocess seems to be stopped, exit code -9
```

**Comment by zhhongzhi** [comment]
```
                try:
                    target_start = sent_tokens.index(target_tokens[0])
                    target_end = sent_tokens[max(0, target_start - 1):].index(target_tokens[-1])  + max(0, target_start - 1)
                except:
                    # error
                    # pdb.set_trace()
                    target_start = 0
                    target_end = 1
                    print u'error'

                if target_start < 0 or target_end < 0:
                    target_start = 0
                    target_end = 1
                    print u'error'
```
corresponding lines is revised... 
Then about 3 lines have error aspect index.

**Comment by berlino** [comment]
Yes, it is probably because the target words are not correctly indexed. You can just ignore these examples.

**Comment by zhhongzhi** [comment]
@berlino Thank you for your kind reply.
